[dependencies]
"php/php" = "8.3.4"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-d","memory_limit=2048M", "-S", "localhost:8080", "-t", "/app/web"]
